### ISSUE TITLE
Where should I add topics that don't fit neatly into your legend/outline? 

### ISSUE THREAD

**Issue by NKSBarker** [borealbirds/bamguide#1]
E.g., Geonetwork and distribution of data products.

**Comment by NKSBarker** [comment]
https://docs.google.com/document/d/1LMr3G7veks0WXXtiSYDxt3_xNTA9G--dyIFNMi7NYV4/edit#

**Comment by psolymos** [comment]
I'd say that would be #5, sharing results & outreach. I.e. developing web reports, products, web apps, geo catalogs etc (which would be more of an overview, not necessarily a reproducible guide).

Note also: we can write all of these in blog-sized units...

**Comment by NKSBarker** [comment]
Steve VW requests: "A speed talk running through the BAM database/ analysis flow (reflecting stuff not yet in tutorials) or Q&A for Peter/Trish that could address questions that come to mind when people try working with DB that we may all have? I could try getting in to the data again and see what stumbling blocks I encountered."

He said this before knowing about our planned skunkworks. But you could potentially incorporate these ideas into your Monday AM session

**Comment by tati-micheletti** [comment]
I updated the README to reflect the googlesheets. Think this issue is closed now. :)
